name: pytest run for wrappers

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install poetry and pytest
      run: |
        pipx install poetry
        pip install pytest

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'poetry'

    - name: Set up poetry
      run: poetry install

    - name: Run tests
      run: |
        poetry run pytest
