name: pytest run for wrappers

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        python-version: ['3.10']

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install global dependencies
        run: |
          pipx install poetry
          pip install pytest

      - name: Run tests
        run: |
          poetry install
          poetry shell
          poetry run pytest -v
